# This action will copy changes from main into the next-minor branch, and is done whenever the main branch is updated.
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  merge-to-next-minor:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for Git to create a pull request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: next-minor

    - name: Merge changes from main
      run: |
        git fetch
        git merge origin/main

    - name: Set git config
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        git config -l

    - name: Check for diffs
      id: diff
      run: |
        git diff --quiet origin/next-minor extracted-files || echo "::set-output name=status::changed"
      shell: bash

    - name: Create Pull Request
      if: steps.diff.outputs.status == 'changed'
      run: |
        git add extracted-files
        git commit -m "Update extracted files"
        git push origin cicd/propagate-main-to-next
        gh pr create -B cicd/propagate-main-to-next -H main --title 'Copy changes from main to next-minor' --body 'Copy changes from main to next-minor\nThis PR is auto-generated by [gh pr create].' --label 'automated pr' --delete-branch
      env:
        GITHUB_TOKEN: $ { { secrets.GITHUB_TOKEN }}
